# Generated by Django 4.0.4 on 2022-04-26 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='code')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='description')),
                ('prof_real', models.PositiveIntegerField(blank=True, null=True)),
                ('prof_intell', models.PositiveIntegerField(blank=True, null=True)),
                ('prof_soc', models.PositiveIntegerField(blank=True, null=True)),
                ('prof_conv', models.PositiveIntegerField(blank=True, null=True)),
                ('prof_entre', models.PositiveIntegerField(blank=True, null=True)),
                ('prof_art', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
