# Generated by Django 3.0.5 on 2022-04-30 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20220427_2211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sphere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('desc', models.CharField(max_length=500, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=50, verbose_name='Tag name')),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='prof_art',
        ),
        migrations.RemoveField(
            model_name='course',
            name='prof_conventional',
        ),
        migrations.RemoveField(
            model_name='course',
            name='prof_initiative',
        ),
        migrations.RemoveField(
            model_name='course',
            name='prof_intellect',
        ),
        migrations.RemoveField(
            model_name='course',
            name='prof_real',
        ),
        migrations.RemoveField(
            model_name='course',
            name='prof_social',
        ),
        migrations.AddField(
            model_name='course',
            name='tag_1',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='tag'),
        ),
        migrations.AddField(
            model_name='course',
            name='tag_2',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='tag'),
        ),
        migrations.AddField(
            model_name='course',
            name='tag_3',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='tag'),
        ),
    ]
