# Generated by Django 3.0.5 on 2022-04-27 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20220426_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='subj',
            name='prof_art',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subj',
            name='prof_conventional',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subj',
            name='prof_initiative',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subj',
            name='prof_intellect',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subj',
            name='prof_real',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subj',
            name='prof_social',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
